const languages: string[] = [
  'Inglês',
  'Chinês Mandarim',
  'Hindi',
  'Espanhol',
  'Francês',
  'Árabe',
  'Bengali',
  'Russo',
  'Português',
  'Indonésio',
  'Urdu',
  'Alemão',
  'Japonês',
  'Suaíli',
  'Marati',
  'Telugu',
  'Punjabi Ocidental',
  'Wu (Shanghainês)',
  'Tâmil',
  'Turco',
  'Coreano',
  'Vietnamita',
  'Chinês Yue (Cantonês)',
  'Javanês',
  'Italiano',
  'Egípcio Árabe',
  'Hauçá',
  'Tailândes',
  'Guzerate',
  'Canarim',
  'Persa',
  'Bhojpuri',
  'Chinês Min Nan (Hokkien-Taiwanês)',
  'Hakka',
  'Chinês Jinyu',
  'Filipino (Tagalo)',
  'Birmanês',
  'Polonês',
  'Iorubá',
  'Oriá',
  'Ucraniano',
  'Maithili',
  'Romeno',
  'Holandês',
  'Tagalo',
  'Grego',
  'Checo',
  'Sueco',
  'Húngaro',
  'Camaronês',
  'Norueguês',
  'Finlandês',
  'Dinamarquês',
  'Eslovaco',
  'Búlgaro',
  'Croata',
  'Lituano',
  'Esloveno',
  'Hebraico',
];

export default languages.sort((a, b) => a.localeCompare(b, 'pt-BR'));
